
name: 3rd Party Addons PR Validator
on:
  workflow_dispatch:
  push:
    paths:
      - 'assets/addon_browser/'
      - '.github/workflows/addons-pr-validator.yml'
  pull_request:
    paths:
      - 'assets/addon_browser/'

permissions:
  contents: read

jobs:
  addons-pr-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 11

      - name: Clone Validator Tool
        run: git clone https://github.com/TechnicJelle/BlueMap3rdValidator.git

      - name: Run the Validator
        run: |
          cd BlueMap3rdValidator
          ./gradlew build
          java -jar build/libs/shadow-1.0-all.jar ".."
